const SCENE_NAMES = {
  // Scene name
  ADD_TASK: 'ADD_TASK_SCREEN',
  LIST_TASK: 'LIST_TASK_SCREEN',
  LAND_DETAIL: 'LAND_DETAIL_SCREEN',
  PROCESS_DETAIL: 'PROCESS_DETAIL_SCREEN',
  ADD_PRODUCT_TO_LAND: 'ADD_PRODUCT_TO_LAND_SCREEN',
  CREATE_LAND: 'CREATE_LAND_SCREEN',
  WEATHER_AND_FORECAST: 'WEATHER_AND_FORECAST_SCREEN',
  LAND_LIST: 'LAND_LIST_SCREEN',
  PROCESS_LIST: 'PROCESS_LIST_SCREEN',
  PRODUCT_LIST: 'PRODUCT_LIST_SCREEN',
  ACCOUNT: 'ACCOUNT_SCREEN',
  HOME: 'HomeScreen',
  MAIN: 'MainScreen',
  SIGN_IN: 'SignInScreen',
  GET_START: 'FilterContainer',
  DUMMY: 'DUMMY_SCREEN',
  FILTER: 'FILTER_SCREEN',
};

export default SCENE_NAMES;
